language:
- objective-c
- c++
compiler:
- clang
sudo: false
os: osx
osx_image: xcode7.3
script:
- mkdir build
- cd build
- cmake -G Xcode ..
- cmake --build .
- cd ..
- PACKAGE_NAME=`echo $TRAVIS_REPO_SLUG | sed 's/.*\///g'`
- PACKAGE_REV=`echo $TRAVIS_COMMIT | sed -e 's/^[[:alnum:]]\{6\}/&-/g' | sed 's/-.*//'`
- PAYLOAD=`( cat ./slack_payload.json)`
- PAYLOAD_PARSE=$(echo $PAYLOAD | sed -e "s/\$PACKAGE_NAME/$PACKAGE_NAME/g" -e "s/\$PACKAGE_REV/$PACKAGE_REV/g" -e "s:\$TRAVIS_REPO_SLUG:$TRAVIS_REPO_SLUG:g" -e "s/\$TRAVIS_BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/g" -e "s/\$PACKAGE_REV/$PACKAGE_REV/g")
- mkdir $PACKAGE_NAME
- if [ -e *.json ]; then cp *.json $PACKAGE_NAME; fi
- if [ -e *.md ]; then cp *.json $PACKAGE_NAME; fi
- if [ -e *.png ]; then cp *.json $PACKAGE_NAME; fi
- if [ -d docs ]; then cp -r docs $PACKAGE_NAME; fi
- if [ -d externals ]; then cp -r externals $PACKAGE_NAME; fi
- if [ -d extras ]; then cp -r extras $PACKAGE_NAME; fi
- if [ -d help ]; then cp -r help $PACKAGE_NAME; fi
- if [ -d init ]; then cp -r init $PACKAGE_NAME; fi
- if [ -d javascript ]; then cp -r javascript $PACKAGE_NAME; fi
- if [ -d media ]; then cp -r media $PACKAGE_NAME; fi
- if [ -d misc ]; then cp -r misc $PACKAGE_NAME; fi
- if [ -d patchers ]; then cp -r help $PACKAGE_NAME; fi
- if [ -d java-classes ]; then cp -r java-classes $PACKAGE_NAME; fi
- if [ -d java-doc ]; then cp -r java-doc $PACKAGE_NAME; fi
- mkdir dist
- zip -q -r dist/$PACKAGE_NAME-$PACKAGE_REV.zip $PACKAGE_NAME
secure: "XSY3BXw4/DmoOy35XT9B3V69JUxKRnP21/GabUm/8zWAB+WC9u5Ybc7hRXpQYT2JT9VN8JxkMcHCZ6bALc/1yg9Yfg72ky9UNq459vuF1FJ00+hH0ayll/VH9NFpPpezxYhgSgrnkCQdWCKSCBj03Sf/f1JsrLv9AereKCDR6cw="
deploy:
  provider: s3
  access_key_id: AKIAIWE3SI2TMXC5AJBA
  secret_access_key:
    secure: oAw/TyIFPf8fcFnLny4NlMYWg8bSPwUOphJ0ZpZk2288H5FvNSo3ohLW1i2LjNRPcpOEzG7yp3mEuwrXqA84mCd9TRpTt23u8VeSlLAZ/hSJr9cv2/py0K3jnSDJb5VvNGdUG+fgJ2GInFZyLm7yqSt6MNqmJ+NUoyZ/bWsyVPs=
  bucket: cycling74-ci
  skip_cleanup: true
  local-dir: dist
  upload-dir: max-mxj
  acl: public_read
  on:
    repo: Cycling74/max-mxj
after_deploy:
  - curl -X POST -H "Content-type:application/json" --data "$PAYLOAD_PARSE" $SLACK_HOOK
notifications:
  slack:
    secure: WV3Cx0m0epgwlVdY7LXPeVPwUfAWbile1nDbwc0qQ5Z8bPo1yhNQnSXTKv6SNOj4aqZLCw3KOuE6eKf37907J0ZV4pv6GGgrEwi4TK7PMF3hnPgoXhCTQjqYr0fqWD2egCOHRGwoZ+LvVKeHzMIFqEWmOyMUgMWzR/BNsX3VyGI=
