#version: '7.2.0.{build}'

environment:
  CMAKE_PATH: $(APPVEYOR_BUILD_FOLDER)\cmake-3.4.1-win32-x86
  VS_VERSION: "Visual Studio 14"
configuration: Release
shallow_clone: false

platform:
  - x86
  - x64
  
build_script:
  - if "%platform%" == "x86" SET VS_FULL=%VS_VERSION%
  - if "%platform%" == "x86" SET CUSTOM_FLAG=""
  - if "%platform%" == "x64" SET VS_FULL=%VS_VERSION% Win64
  - if "%platform%" == "x64" SET CUSTOM_FLAG="-DWIN64:Bool=True"
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  - mkdir %APPVEYOR_PROJECT_NAME%
  - cp -r externals %APPVEYOR_PROJECT_NAME%
  - cp -r help %APPVEYOR_PROJECT_NAME%
  - cp License.md %APPVEYOR_PROJECT_NAME%
  - cp ReadMe.md %APPVEYOR_PROJECT_NAME%
  - 7z a %APPVEYOR_PROJECT_NAME%-win-%platform%-%APPVEYOR_REPO_COMMIT%.zip %APPVEYOR_PROJECT_NAME% > %APPVEYOR_BUILD_FOLDER%\archive.log

artifacts:
  - name: Build
    path: '*.zip'
  - name: Log files
    path: '*.log'

deploy:
  provider: S3
  access_key_id: AKIAIWE3SI2TMXC5AJBA
  secret_access_key:
    secure: PXJw4guo+r6IdUYK6t8rW01Gi0mWHPmyH+Pa6UmZePtgV1iXaZYoO2R9CgoCQ80y
  bucket: cycling74-ci
  folder: max-mxj
  region: us-west-2
  set_public: true
  artifact: "$(APPVEYOR_PROJECT_NAME)-win-$(platform)-$(APPVEYOR_REPO_COMMIT).zip"
