/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cycling74_max_MaxObject */

#ifndef _Included_com_cycling74_max_MaxObject
#define _Included_com_cycling74_max_MaxObject
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef com_cycling74_max_MaxObject_MAX_INLETS
#define com_cycling74_max_MaxObject_MAX_INLETS 7L
#undef com_cycling74_max_MaxObject_MAX_OUTLETS
#define com_cycling74_max_MaxObject_MAX_OUTLETS 7L
/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doPost
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_cycling74_max_MaxObject_doPost
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doError
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_cycling74_max_MaxObject_doError
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doOuch
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_cycling74_max_MaxObject_doOuch
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doGetMaxVersion
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_cycling74_max_MaxObject_doGetMaxVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doOutlet
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cycling74_max_MaxObject_doOutlet__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doOutlet
 * Signature: (IF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cycling74_max_MaxObject_doOutlet__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doOutlet
 * Signature: (ILjava/lang/String;[Lcom/cycling74/max/Atom;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cycling74_max_MaxObject_doOutlet__ILjava_lang_String_2_3Lcom_cycling74_max_Atom_2
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     com_cycling74_max_MaxObject
 * Method:    doOutlet
 * Signature: (I[Lcom/cycling74/max/Atom;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cycling74_max_MaxObject_doOutlet__I_3Lcom_cycling74_max_Atom_2
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
